### ISSUE TITLE
Missing guide how to get running

### ISSUE THREAD

**Issue by bernermic** [pzmarzly/sshfs-manager#1]
Hey,
the Readme does not make it clear how to get the sfs running.
It would help if you could explain how the installation is done.
Thanks :)

**Comment by pzmarzly** [comment]
Hi. Thanks for being interested in my code and for reaching out. I didn't expect anyone to find this project, as it's just a quickly hacked solution to a problem I had (sshfs requiring too many lines to make a mount that's both fast and easy to use, as in not having weird permission issues). In the end I didn't put much effort into it, only made sure it works with standard VPSes.

I just updated the README, and added `rust-toolchain` file to remove an extra installation step.

I guess the major strength this script has is a short command to mount/unmount (`sshfs 11.22.33.44` or `sshfs myserver`, even when you are connecting to that server for the first time).

That being said, you may be also interested in alternatives such as `rclone` with [SFTP](https://rclone.org/sftp/) backend.

**Comment by bernermic** [comment]
Thanks for your answer! I'll close this then as resolved.
